# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a62d5364422b640820e7c372057e3f4ecfca58d6b31d4d776082bc9fb153b40c830b0297edfadbad06a832c601b701837acb40e42dfbb37726698347b28f9ff

test:
  secret_key_base: d86feea5fee13722c1f78ea0a28794a7c4afbd43e596b1148267d48d2bb97a262c6d324b98ef6247177d5f643273eb0068f752cef369059e3cf2cdceeae8b2d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
